Integer and float numbers
AndrewErmakov/PythonTrainingBasics pull request #2
Opened 2018-10-18 20:29 UTC by AndrewErmakov

2018-10-19 07:26 UTC, akhtyamovpavel requested changes

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Apple sharing.py
> +n = int(input())
Что такое переменная `n`? Если это количество яблок, то лучше писать `apples`

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Apple sharing.py
> +k = int(input())
Аналогично с переменной `k`

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Apple sharing.py
> +apples_for_student = k//n
Разделяем символы - `k // n`

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Area of right-angle triangle.py
> +b = int(input())
Аналогично - что такое `b` и `h`?

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Area of right-angle triangle.py
> +s= b * h /2
Пробелы до и после знака =

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Area of right-angle triangle.py
> +print(s)
Не хватает перевода строки - Github сам это помечает. И что такое s?

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Hello,Harry!.py
> +print ('Hello'+','+' '+ name + '!' )
Не хватает пробелов между знаками +
Нет перевода строки
Между print и скобкой не должно быть пробелов

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Hi John.py
> +print('Hi '+name)
Аналогично `Hello Harry`

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Previous and next.py
> +print("The next number for the number "+str(number)+' '+'is '+str(number+1))
В Python нет разницы, какие кавычки ставить - давай определим один вид и будем ставить их

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/School desks.py
> +number_of_classmates1= int(input())
Пробела не хватает

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/School desks.py
> +print(number_of_classmates1//2 + number_of_classmates1% 2+ number_of_classmates2//2 + number_of_classmates2 % 2+number_of_classmates3//2 + number_of_classmates3% 2 )
Форматирование - пробелы между знаками, перевод конца строки

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/School desks.py
> +number_of_classmates2= int(input())
Что такое `number_of_classmates2`, можно дать более интеллектуальное название?

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/SumOfThreeNumbers.py
> +print(a + b + c)
Поставь перевод строки - а так, все хорошо по этому файлу

2018-10-19 07:26 UTC, akhtyamovpavel commented on InputOutputNumbers/Two timestamps.py
> +print(3600*(number_of_hours2-number_of_hours1)+60*(number_of_minutes2-number_of_minutes1)+(number_of_seconds2-number_of_seconds1))
Отформатируй строку с пробелами, и будет хорошо.
Перевода строки нет

2018-10-19 07:31 UTC, AndrewErmakov commented on InputOutputNumbers/Area of right-angle triangle.py
> +print(s)
S-площадь треугольника

2018-10-19 07:32 UTC, AndrewErmakov commented on InputOutputNumbers/Previous and next.py
> +print("The next number for the number "+str(number)+' '+'is '+str(number+1))
Одинарные

2018-10-19 07:33 UTC, AndrewErmakov commented on InputOutputNumbers/School desks.py
> +number_of_classmates2= int(input())
Например?

2018-10-20 15:57 UTC, akhtyamovpavel approved these changes

2018-10-20 15:57 UTC, akhtyamovpavel commented on InputOutputNumbers/Apple sharing.py
> +apples_for_student = k // n
Не работае

2018-10-20 15:57 UTC, akhtyamovpavel commented on InputOutputNumbers/Area of right-angle triangle.py
> +areaOfTriangle = b * h / 2
Тоже не работает

2018-10-20 15:57 UTC, merged