Develop
AndrewErmakov/PythonTrainingBasics pull request #3
Opened 2018-10-23 12:36 UTC by AndrewErmakov

Вторая тема

2018-10-23 15:06 UTC, akhtyamovpavel requested changes
Проверил код, уже лучше, но есть, к чему стремиться

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Bishop moves (chess).py
> +if (math.fabs(x2 - x1) == math.fabs(y2 - y1)):
Убираем скобки:
``` math.fabs(x2 - x1) == math.fabs(y2 - y1)```

А почему `fabs`, а не `abs`?

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Bishop moves (chess).py
> +    print('NO')
Перевод в конце строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Chess board - same color.py
> +if ((x1 + y1) % 2 == 0) and ((x2 + y2) % 2 == 0) or ((x1 + y1) % 2 == 1) and ((x2 + y2) % 2 == 1):
Опять же скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Chess board - same color.py
> +    print('NO')
Перевод в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Chocolate bar.py
> +n = int(input())
Что такое `n, m, k`?

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Chocolate bar.py
> +if ((k % n == 0) or (k % m == 0)) and (k < m * n):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Chocolate bar.py
> +    print('NO')
Перевод в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Equal numbers.py
> +if (a == b == c):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Equal numbers.py
> +elif (a == b) or (a == c) or (b == c):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/King move (chess).py
> +
Лишняя строка

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/King move (chess).py
> +if (math.fabs(x2 - x1) == 1) and (math.fabs(y2 - y1) == 1):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/King move (chess).py
> +elif (math.fabs(x2 - x1) == 1) and (math.fabs(y2 - y1) == 0):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Leap year.py
> +if (year % 4 == 0) and (year % 100 != 0):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Leap year.py
> +    print('COMMON')
Перевод строки в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Minimum of three numbers.py
> +min = a
`min`?

Лучше использовать другую переменную, потому что `min` - это функция

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Minimum of three numbers.py
> +if (b < min):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Minimum of two numbers.py
> +if (number2 < number1):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Minimum of two numbers.py
> +min = number1
`min` - ключевое слово

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Queen move (chess).py
> +if (abs(x2 - x1) == abs(y2 - y1)):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Rook move.py
> +Horiz1 = int(input())
`Horizontal, Vertical`

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Rook move.py
> +if (Horiz1 == Horiz2) or (Vertic1 == Vertic2):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Conditions- if, then, else/Rook move.py
> +    print('NO')
Перевод в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Adding factorials.py
> +    sum += factorial
`sum` - ключевое слово, лучше заменить на другую переменную

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Factorial.py
> +print(factorial)
Перевод в конце строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Lost card.py
> +numberOfCards = int(input())
Давай учиться именованию в python

Можно так, но лучше `number_of_cards`

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Lost card.py
> +print(sum)
Перевод файла в конце строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Lost card.py
> +sum = 0
`sum` - ключевое слово, лучше заменить

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Series -1.py
> +a = int(input())
Что такое `a, b`? Лучше заменить на `from_range`, `to_range`

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Series -2.py
> +if (a < b):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Series -2.py
> +a = int(input())
Что такое `a, b`?

Может, лучше `from_range, to_range`?

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Series -2.py
> +if (a >= b):
Скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Series -2.py
> +        print(i)
Перевод строки в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Sum of N numbers.py
> +sum = 0
`sum` - ключевое слово, лучше заменить

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Sum of cubes.py
> +sum = 0
Аналогично, заменить

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Sum of cubes.py
> +    #number=i
Закомментированный код не оставляем в Github

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Sum of cubes.py
> +print(sum)
Перевод строки в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Sum of ten numbers.py
> +sum = 0
`sum` - ключевое слово, заменить

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/Sum of ten numbers.py
> +print(sum)
Перевод строки в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/The number of zeros.py
> +countOfZero = 0
`count_of_zero`

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/The number of zeros.py
> +    if (number == 0):
Лишние скобки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Car route.py
> +print(days)
Перевод строки в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on For loop with range/The number of zeros.py
> +print(countOfZero)
Перевод строки в конце файла

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Car route.py
> +days = math.ceil(wayInKilometres/speedPerDay)
Забыл пробел в `/`

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Clock face -2.py
> +Hours = alpha // 30
`hours` - переменные именуем в одном стиле

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Clock face -2.py
> +Minuts = alpha % 30
`minutes` - один стиль + орфографическая ошибка

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Clock face -2.py
> +betta =(12 * Minuts) % 360
Не хватает пробела после =

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Clock face -2.py
> +betta =(12 * Minuts) % 360
beta

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Clock face-1.py
> +Hours = int(input())
`hours`, `minutes`, and `seconds`

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Digital clock.py
> +nunberOfMinutes = int(input())
`number_of_minutes`

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Digital clock.py
> +print(hoursInDigitalClock, minutesInDigitalClock)
Перевод строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/First digit after decimal point.py
> +print(int(number * 10 % 10))
Перевод строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Fractional part.py
> +print(number - int(number))
Перевод строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Last digit of integer.py
> +print(number % 10)
Перевод строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Sum of digit.py
> +print((number % 10) + (number // 10 % 10)+(number // 100))
Перевод строки + скобки.

Лучше завести переменную, где будет вычисление этого выражения

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Tens digit.py
> +print(number // 10 % 10)
Перевод строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Total cost.py
> +print(allDollarsForAllCupcakes, allCentsForAllCupcakes)
Перевод строки

2018-10-23 15:06 UTC, akhtyamovpavel commented on Integer and float numbers/Total cost.py
> +dollarsForACupcake = int(input())
`dollars_for_cupcake` - `a` лишний, он не несет никакого смысла

2018-10-24 07:53 UTC, AndrewErmakov commented on Conditions- if, then, else/Chocolate bar.py
> +n = int(input())
В условии написаны

2018-10-24 07:55 UTC, AndrewErmakov commented on Integer and float numbers/Total cost.py
> +dollarsForACupcake = int(input())
Вообще то мы вводим это значение

2018-10-24 07:56 UTC, AndrewErmakov commented on Integer and float numbers/Digital clock.py
> +nunberOfMinutes = int(input())
Ты меня учил называть переменные типа nunberOfMinutes

2018-10-25 13:31 UTC, akhtyamovpavel commented on Conditions- if, then, else/Chocolate bar.py
> +n = int(input())
Код должен быть понятен без условия

2018-10-25 13:31 UTC, akhtyamovpavel commented on Integer and float numbers/Total cost.py
> +dollarsForACupcake = int(input())
Не, я про то, что dollars_for_cupcake

2018-10-26 06:03 UTC, AndrewErmakov commented on Conditions- if, then, else/Bishop moves (chess).py
> +if (math.fabs(x2 - x1) == math.fabs(y2 - y1)):
ИСправил

2018-10-26 06:04 UTC, AndrewErmakov commented on Conditions- if, then, else/Chess board - same color.py
> +if ((x1 + y1) % 2 == 0) and ((x2 + y2) % 2 == 0) or ((x1 + y1) % 2 == 1) and ((x2 + y2) % 2 == 1):
Везде исправил скобки

2018-10-26 06:04 UTC, AndrewErmakov commented on Integer and float numbers/Sum of digit.py
> +print((number % 10) + (number // 10 % 10)+(number // 100))
Завел переменную

2018-10-26 06:05 UTC, AndrewErmakov commented on Conditions- if, then, else/Minimum of three numbers.py
> +min = a
Например? А что за функция min?

2018-10-26 06:06 UTC, AndrewErmakov commented on Conditions- if, then, else/Rook move.py
> +Horiz1 = int(input())
Сократил

2018-10-26 06:06 UTC, AndrewErmakov commented on For loop with range/Adding factorials.py
> +    sum += factorial
Что такое sum ключевое слово?

2018-10-26 06:06 UTC, AndrewErmakov commented on For loop with range/Lost card.py
> +numberOfCards = int(input())
Почему нельзя как я?

2018-10-27 18:44 UTC, akhtyamovpavel approved these changes

2018-10-27 18:44 UTC, akhtyamovpavel commented on Conditions- if, then, else/Knight move (chess).py
> +if (abs(x2 - x1) == 2 and abs(y2 - y1) == 1) or (abs(x2 - x1) == 1 and (abs(y2 - y1) == 2)):
Скобки не убраны

2018-10-27 18:44 UTC, merged