Added fifth theme
AndrewErmakov/PythonTrainingBasics pull request #4
Opened 2018-10-30 13:52 UTC by AndrewErmakov

2018-10-30 17:15 UTC, akhtyamovpavel approved these changes

2018-10-30 17:15 UTC, akhtyamovpavel commented on Strings/Replace within a fragment.py
> +newSentence = sentence[:indexOfFirstLetter+1] + partOfSentenceWithH + sentence[indexOfLastLetter:]
:indexOfLastLetter + 1

2018-10-30 17:15 UTC, akhtyamovpavel commented on Strings/The second occurence.py
> +    secondPartOfSentence = sentence[firstIndexOfLetterF+1:]
firstIndexOfLetterF + 1

2018-10-30 17:15 UTC, akhtyamovpavel commented on Strings/The two halves.py
> +partOfSentence1 = sentence[math.ceil(0.5 * len(sentence)):len(sentence)]
Давай вынесем `math.ceil(0.5 * len(sentence))` в отдельную переменную

2018-10-30 17:15 UTC, akhtyamovpavel commented on Strings/Remove the fragment.py
> +partOfSentence = sentence[sentence.find('h'):sentence.rfind('h')+1:]
`sentence.rfind('h') + 1:`

2018-10-31 06:15 UTC, akhtyamovpavel requested changes
Проверил код. Будем говорить теперь про именование переменных

2018-10-31 06:15 UTC, akhtyamovpavel commented on While loop/The power of two.py
> +x = 0
Что такое `x`?

2018-10-31 06:15 UTC, akhtyamovpavel commented on While loop/The second maximum.py
> +element1 = element2 = 0
Что такое `element1` и `element2`?

2018-10-31 06:15 UTC, akhtyamovpavel commented on While loop/The number of even elements of the sequence.py
> +number = int(input())
Отличное решение!

2018-10-31 06:15 UTC, akhtyamovpavel commented on While loop/The number of elements that are greater than the previous one.py
> +countOf2x = 0
`count_of_two_x`, и что это за переменная?

2018-10-31 06:15 UTC, akhtyamovpavel commented on While loop/The maximum number of consecutive equal elements.py
> +number1 = int(input())
Что такое `number1`, `number2`?

2018-10-31 06:15 UTC, akhtyamovpavel commented on While loop/The index of a Fibonacci number.py
> +a = int(input())
Что такое `a`?

2018-10-31 06:15 UTC, akhtyamovpavel commented on While loop/Fibonacci numbers.py
> +fib1 = fib2 = 1
Что такое `fib1`, `fib2`?

2018-10-31 06:30 UTC, AndrewErmakov commented on While loop/Fibonacci numbers.py
> +fib1 = fib2 = 1
Элемент фибоначчи в формуле

2018-10-31 06:33 UTC, AndrewErmakov commented on While loop/The index of a Fibonacci number.py
> +a = int(input())
Введенное число. Необходимо узнать, является ли числом Фибоначчи

2018-10-31 06:34 UTC, AndrewErmakov commented on While loop/The number of elements that are greater than the previous one.py
> +countOf2x = 0
ЧИСЛО ЭЛЕМЕНТОВ КОТОРОЕ БОЛЬШЕ ЧЕМ предыдущее

2018-10-31 06:35 UTC, AndrewErmakov commented on While loop/The second maximum.py
> +element1 = element2 = 0
Второй максимум

2022-04-27 20:02 UTC, closed without merging